name: oda

services:
  topicmanager:
    build:
      context: src/topic_manager
      dockerfile: DockerfileARM
  datapump:
    build:
      context: src/data_pump
      dockerfile: DockerfileARM
